// Generated by https://quicktype.io

export interface MockData {
  item_code: number;
  material_code: string;
  legacy: string;
  short_discription: string;
  long_discription: LongDiscription;
  noun: string;
  modifier: string;
  status: boolean;
}

export enum LongDiscription {
  ErrorUndefinedMethodForNilNilClass = "error: undefined method `/' for nil:NilClass",
}
