// Generated by https://quicktype.io

export interface MockData {
  item_code: number;
  material_code: string;
  legacy: string;
  short_discription: string;
  long_discription: LongDiscription;
  noun: string;
  modifier: string;
  status: boolean;
}

export enum LongDiscription {
  ErrorUndefinedMethodForNilNilClass = "error: undefined method `/' for nil:NilClass",
}

// Generated by https://quicktype.io

export interface PostCreateFieldData {
  id: string;
  type: string;
  identity?: string;
  name: string;
  pattern?: string;
  min?: number;
  max?: number;
  minLength?: number;
  maxLength?: number;
  extraField?: boolean;
  readable?: boolean;
  writable?: boolean;
  showAsColumn?: boolean;
  enumValues?: string[];
  fieldLabel?: FieldLabel;
  required: boolean;
  options?: Option[];
  value?: string;
}

export interface FieldLabel {
  label?: string;
}

export interface Option {
  id?: string;
  value: string;
}
